version: '3'
services:
  backend:
    depends_on:
      - db
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.backend
    volumes:
      - ../backend:/app
      - ../backend/static/data/images:/app/static/data/images
      - /app/i18n
    ports:
      - "80:80"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    #command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    command: bash -c "flask run --host=0.0.0.0 --port=80 && while true; do echo 'sleeping...' && sleep 10; done"
  db:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.db
    ports:
      - "5433:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=geopaysages
      - POSTGRES_PASSWORD=password
      - POSTGRES_SERVER=db
      - POSTGRES_USER=root

volumes:
  app-db-data: