version: '3'
services:
  imaginary:
    image: h2non/imaginary:latest
    # optionally mount a volume as local image source
    volumes:
      - ${VOLUME_PATH}/upload:/mnt/data
    environment:
       PORT: 9000
    command: -enable-url-source -mount /mnt/data
    ports:
      - "9000:9000"
  backend:
    container_name: geopaysage_backend
    depends_on:
      - db
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.backend
    volumes:
      - ../backend:/app
      - ${VOLUME_PATH}/upload:/upload
    ports:
      - "${HTTP_PORT}:80"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    #command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    command: bash -c "/app/prestart.sh && flask run --host=0.0.0.0 --port=80 && while true; do echo 'sleeping...' && sleep 10; done"
  db:
    container_name: geopaysage_db
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.db
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - geopaysages-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=geopaysages
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_SERVER=db
      - POSTGRES_USER=root

volumes:
  geopaysages-db-data: